vich_uploader:
    db_driver: orm

    mappings:
       realisation_image:
           uri_prefix: '%realisation_image%'
           upload_destination: '%kernel.project_dir%/public%realisation_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
